name: Publish

on:
  release:
    types:
      - created


jobs:
  update-version-and-changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - name: Update version file
        run: |
          cat VERSION
          echo "VERSION ${{ github.ref_name }}"
          echo -n "${{ github.ref_name }}" > VERSION
      - name: Update changelog file
        run: |
          echo "CHANGELOG"
      - name: Commit updated files
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git add VERSION CHANGELOG.md
          git commit -m "Auto version and changelog update [${{ github.ref_name }}]"
          git push origin
      - name: Tag new commit
        run: |
          git tag --force ${{ github.ref_name }}
          git push origin ${{ github.ref_name }} --force

  update-release-github:
    needs: update-version-and-changelog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}
      - name: Update Release description
        run: |
          echo "VERSION"
          echo "CHANGELOG"

  release-python-package:
    needs: update-version-and-changelog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}
      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: 'pip' # caching pip dependencies
      - name: Build python package
        run: |
          python -m pip install wheel build twine
          python -m pip wheel . --no-deps --wheel-dir dist
          twine upload -u __token__ -p ${{ secrets.PYPI_TOKEN }} dist/*
